{
 "title": "Hermes dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "request_id", "query": { "query": "label_values(id)" } }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success ratio (last)",
   "type": "gauge",
   "description": "Shows the percentage of requests that were answered with expected result codes",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hermes_responses_rcv_ok{id=~\"$request_id\"}) / sum(hermes_requests_sent{id=~\"$request_id\"}) *100"
    }
   ]
  },
  {
   "title": "Requests sent/s (last)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(hermes_requests_sent{id=~\"$request_id\"}))"
    }
   ]
  },
  {
   "title": "Response times (ms)",
   "type": "timeseries",
   "description": "This panel shows the response times in ms of all requests sent by hermes. Only those of expected result codes received are accounted here.",
   "gridPos": { "h": 12, "w": 12, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hermes_response_time_ok_ms_sum{id=~\"$request_id\"}[1m] / hermes_response_time_ok_ms_count{id=~\"$request_id\"}[1m]",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Responses received/s (last)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(hermes_responses_rcv_ok{id=~\"$request_id\"}))"
    }
   ]
  },
  {
   "title": "RT (last)",
   "type": "stat",
   "description": "This gauge shows the latest average of response times in ms of all requests sent by hermes. Only those of expected result codes received are accounted here.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hermes_response_time_ok_ms_sum{id=~\"$request_id\"}[1m] / hermes_response_time_ok_ms_count{id=~\"$request_id\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GET debugging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "GET logs - server",
   "type": "logs",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "_stream: {k8s.container.name=\"server-mock\"} AND \"GET\" | _time:10s"
    }
   ]
  },
  {
   "title": "GET > 10ms",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 14 },
   "targets": [
    { "limit": 1000, "operation": "get1", "service": "hermes" }
   ]
  },
  {
   "title": "GET > 10ms",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "limit": 1000, "operation": "get1", "service": "hermes" }
   ]
  }
 ]
}