serverMock:
  name: server-mock
  replicaCount: 1
  image:
    repository: ghcr.io/jgomezselles/kubecon24/server-mock
    pullPolicy: IfNotPresent
    tag: 0.0.1
  service:
    type: ClusterIP
    port: 8080
  resources: {}

hermes:
  script:
    cm: traffic-script-cm
  image:
    repository: ghcr.io/jgomezselles/hermes
    tag: 0.0.4
    pullPolicy: IfNotPresent
  o11y:
    metrics_endpoint: http://otelcol:4318/v1/metrics
    #http://victoria-svc:8428/opentelemetry/api/v1/push
    traces_endpoint: http://otelcol:4318/v1/traces
    #http://hermes-tempo:4318/v1/traces

victoria-metrics-single:
  server:
    fullnameOverride: "victoria-svc"
    persistentVolume:
      enabled: false

jaeger:
  fullnameOverride: "jaeger-svc"
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true
  storage:
    type: memory
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false

opentelemetry-collector:
  fullnameOverride: "otelcol"
  mode: deployment
  image:
    repository: "otel/opentelemetry-collector-contrib"
  presets:
    clusterMetrics:
      enabled: true
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      debug: {}
      otlphttp/victoriametrics:
        compression: gzip
        encoding: proto
        # Setting below will work for sending data to VictoriaMetrics single-node version.
        # Cluster version of VictoriaMetrics will require a different URL - https://docs.victoriametrics.com/cluster-victoriametrics/#url-format
        endpoint: http://victoria-svc:8428/opentelemetry
        tls:
           insecure: true
      otlp/jaeger:
        endpoint: jaeger-svc-collector:4317
        tls:
           insecure: true

    connectors:
      spanmetrics:

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp/victoriametrics]
        traces:
          receivers: [otlp]
          processors: []
          exporters: [spanmetrics, otlp/jaeger]
        metrics/spanmetrics:
          receivers: [spanmetrics]
          exporters: [otlphttp/victoriametrics]

#grafana:
#  adminPassword: admin
#  datasources:
#    datasources.yaml:
#      apiVersion: 1
#      datasources:
#      - name: Prometheus
#        type: prometheus
#        url: http://victoria-svc:8428
#        access: proxy
#        isDefault: true
#        uid: hermes-prometheus-datasource
#      - name: Tempo
#        uid: tempo
#        type: tempo
#        url: http://hermes-tempo:3100
#        isDefault: false
#      deleteDatasources:
#      - name: Prometheus
#
#  dashboardProviders:
#   dashboardproviders.yaml:
#     apiVersion: 1
#     providers:
#     - name: 'default'
#       orgId: 1
#       folder: ''
#       type: file
#       disableDeletion: false
#       editable: true
#       options:
#         path: /var/lib/grafana/dashboards/default
#
#  dashboardsConfigMaps:
#    default: "hermes-dashboard"
