serverMock:
  name: server-mock
  replicaCount: 1
  image:
    repository: ghcr.io/jgomezselles/kubecon24/server-mock
    pullPolicy: IfNotPresent
    tag: 0.0.1
  service:
    type: ClusterIP
    port: 8080
  resources: {}

hermes:
  script:
    cm: traffic-script-cm
  image:
    repository: ghcr.io/jgomezselles/hermes
    tag: 0.0.4
    pullPolicy: IfNotPresent
  o11y:
    metrics_endpoint: http://otelcol:4318/v1/metrics
    #http://victoria-svc:8428/opentelemetry/api/v1/push
    traces_endpoint: http://otelcol:4318/v1/traces
    #http://hermes-tempo:4318/v1/traces

victoria-metrics-single:
  server:
    fullnameOverride: "victoria-svc"
    persistentVolume:
      enabled: false

jaeger:
  enabled: true
  fullnameOverride: "jaeger-svc"
  provisionDataStore:
    cassandra: false
  allInOne:
    enabled: true
  storage:
    type: memory
  agent:
    enabled: false
  collector:
    enabled: false
  query:
    enabled: false

opentelemetry-collector:
  fullnameOverride: "otelcol"
  mode: deployment
  image:
    repository: "otel/opentelemetry-collector-contrib"
  presets:
    clusterMetrics:
      enabled: true
  config:
    extensions:
      bearertokenauth:
        scheme: "Bearer"
        token:  #My VM cloud token
      health_check:
        endpoint: ${env:MY_POD_IP}:13133

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      debug: {}
      otlphttp/victoriametrics:
        compression: gzip
        encoding: proto
        # Setting below will work for sending data to VictoriaMetrics single-node version.
        # Cluster version of VictoriaMetrics will require a different URL - https://docs.victoriametrics.com/cluster-victoriametrics/#url-format
        # http://victoria-svc:8428/opentelemetry
        endpoint: http://victoria-svc:8428/opentelemetry
        tls:
           insecure: true
      otlphttp/cloud:
        compression: gzip
        encoding: proto
        endpoint: https://gw-c15-1b.cloud.victoriametrics.com/opentelemetry #VMcloud endpoint <url>/opentelemetry
        auth:
          authenticator: bearertokenauth
      otlp/jaeger:
        endpoint: jaeger-svc-collector:4317
        tls:
           insecure: true

    connectors:
      spanmetrics:

    service:
      extensions: [bearertokenauth, health_check]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp/victoriametrics, otlphttp/cloud ]
        traces:
          receivers: [otlp]
          processors: []
          exporters: [spanmetrics, otlp/jaeger]
        metrics/spanmetrics:
          receivers: [spanmetrics]
          exporters: [otlphttp/victoriametrics]


grafana:
  adminPassword: admin
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://victoria-svc:8428
        access: proxy
        isDefault: true
        uid: hermes-prometheus-datasource
      deleteDatasources:
      - name: Prometheus

  dashboardProviders:
   dashboardproviders.yaml:
     apiVersion: 1
     providers:
     - name: 'default'
       orgId: 1
       folder: ''
       type: file
       disableDeletion: false
       editable: true
       options:
         path: /var/lib/grafana/dashboards/default

  dashboardsConfigMaps:
    default: "hermes-dashboard"
